kind: PersistentVolume
apiVersion: v1
metadata:
  name: sqlonkar
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /onkar

# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: sqlvolpvc
#   namespace: notes-app
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: local-storage